apiVersion: v1
kind: Service
metadata:
  name: dev-env-cache
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: dev-env-cache
  clusterIP: None
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: coder-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: coder
  clusterIP: None
  ports:
  - name: coder
    port: 8080
    targetPort: http-port
  - name: file-browser
    port: 80
    targetPort: file-browser
  - name: web-dev
    port: 8888
    targetPort: dev-port
---
apiVersion: v1
kind: Service
metadata:
  name: coder-staging-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: coder
  clusterIP: None
  ports:
  - name: coder
    port: 8080
    targetPort: http-port
  - name: file-browser
    port: 80
    targetPort: file-browser
  - name: web-dev
    port: 8888
    targetPort: dev-port
