apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
resources:
- ingress.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- secrets.yaml
patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: coder
    namespace: dev
  path: image-patch.json6902.yaml
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: coder
    namespace: dev
  path: volumes-patch-coder.json6902.yaml
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: dev-env-cache
    namespace: dev
  path: volumes-patch-cache.json6902.yaml
